import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { getCookie } from '../cookies';

export default function Home() {
  const router = useRouter()
  
  useEffect(()=>{
    const token = getCookie("token")
    if(!token){
      router.push('/login')
    }else{
      router.push('/home')
    }
  },[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        
      </main>
    </>
  )
}
